// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkd_agSQPr4cxQiEmcZJBU5GVZXTq0aY',
    appId: '1:899335110338:web:cac25d3b25035b7c24055b',
    messagingSenderId: '899335110338',
    projectId: 'decide-app-rusito',
    authDomain: 'decide-app-rusito.firebaseapp.com',
    storageBucket: 'decide-app-rusito.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KFAG-9iJVdNKO1DiR6MzAJnikq68cHw',
    appId: '1:899335110338:android:c9ce63aeec98153524055b',
    messagingSenderId: '899335110338',
    projectId: 'decide-app-rusito',
    storageBucket: 'decide-app-rusito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YHVSDJJZTBTvZ9wTvaRwGLGKx-6l-ck',
    appId: '1:899335110338:ios:c715626c429bf69d24055b',
    messagingSenderId: '899335110338',
    projectId: 'decide-app-rusito',
    storageBucket: 'decide-app-rusito.firebasestorage.app',
    iosBundleId: 'com.tuempresa.decide',
  );
}
